### ISSUE TITLE
Timeout Error with the Also Known As tool

### ISSUE THREAD

**Issue by ryanreso1993** [Soyle-Productions/soyle-stories#101]
1. Open a new project
2. Create a character
3. Open the character profile
4. Select Also Known As
5. Type in a name like "(+_"
6. Hit Enter

What I expect: The nickname will appear in the Character Profile
What actually happens: A timeout error occurs and the following message pops up:

kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
	at java.base/java.lang.Thread.run(Unknown Source)
![image](https://user-images.githubusercontent.com/61167122/123883011-4162f400-d905-11eb-88a8-6d5592c23fe9.png)

**Comment by b-camphart** [comment]
Doesn't require a weird name.  This happens every time you try to create a new name variant

**Comment by b-camphart** [comment]
@ryanreso1993 please verify with new release

**Comment by ryanreso1993** [comment]
Bug fixed!
