### ISSUE TITLE
Changing Perspective Character to Minor Character Creates Error

### ISSUE THREAD

**Issue by ryanreso1993** [Soyle-Productions/soyle-stories#87]
Create two characters: Bob and Alice
Create a character arc for Bob
Open the Character Conflict tool for Bob's arc
Add Alice as an opponent to Bob
Change the perspective to Bob

What I expect to happen:
Then the other character becomes a Major Character

What actually happens:
Then the other character becomes a Major Character, but the program displays this error:

**Error message:**

com.soyle.stories.domain.theme.CharacterIsNotMajorCharacterInTheme
	at com.soyle.stories.usecase.theme.examineCentralConflictOfTheme.ExamineCentralConflictOfThemeUseCase.getMajorCharacter(ExamineCentralConflictOfThemeUseCase.kt:91)
	at com.soyle.stories.usecase.theme.examineCentralConflictOfTheme.ExamineCentralConflictOfThemeUseCase.getExaminedCharacterChange(ExamineCentralConflictOfThemeUseCase.kt:38)
	at com.soyle.stories.usecase.theme.examineCentralConflictOfTheme.ExamineCentralConflictOfThemeUseCase.invoke(ExamineCentralConflictOfThemeUseCase.kt:27)
	at com.soyle.stories.theme.characterConflict.CharacterConflictController$getValidState$1.invokeSuspend(CharacterConflictController.kt:51)
	at com.soyle.stories.theme.characterConflict.CharacterConflictController$getValidState$1.invoke(CharacterConflictController.kt)
	at com.soyle.stories.theme.characterConflict.CharacterConflictController$getValidState$1.invoke(CharacterConflictController.kt)
	at com.soyle.stories.common.AsyncThreadTransformer$async$1$1.invokeSuspend(ThreadTransformerImpl.kt:12)
	at com.soyle.stories.common.AsyncThreadTransformer$async$1$1.invoke(ThreadTransformerImpl.kt)
	at com.soyle.stories.common.AsyncThreadTransformer$async$1$1.invoke(ThreadTransformerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at com.soyle.stories.common.AsyncThreadTransformer$async$1.invokeSuspend(ThreadTransformerImpl.kt:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by b-camphart** [comment]
@ryanreso1993 please verify with new release

**Comment by ryanreso1993** [comment]
> @ryanreso1993 please verify with new release

Cannot reproduce, unable to locate Character Conflict Tool from Character Arc

**Comment by b-camphart** [comment]
Take a look in the theme list tool

**Comment by ryanreso1993** [comment]
Still running into error. Kindly advise. 

Can:
Create two characters Bob and Alice
Create a theme
Right click the theme and open Examine Central Conflict 
Open the Character Conflict tool for Bob's arc

Cannot: 
Add Alice as an opponent to Bob
Change the perspective to Bob

**Comment by b-camphart** [comment]
Right now, the only perspective characters you can select are characters in the theme.  Should the menu look like this instead:

> Major Characters
> Minor Characters
> Other Characters in Project
> Create New Character

Would that make sense?

**Comment by ryanreso1993** [comment]
Ok yes I think that’s clearer and points the user better.
