### ISSUE TITLE
Character Conflict Tool Error when Filling Fields

### ISSUE THREAD

**Issue by ryanreso1993** [Soyle-Productions/soyle-stories#88]
Create two characters, Bob and Alice
Create an arc for a character
Open the Character Conflict Tool
Fill in Central Conflict, Desire, Psychological Weakness

What I expect to happen:
Fill in Moral Weakness

What actually happens: 
When clicking on the Moral Weakness field or around it, the following error comes up:

java.lang.NullPointerException
	at com.soyle.stories.usecase.character.arc.section.changeCharacterArcSectionValue.ChangeCharacterMoralWeaknessUseCase.invoke(ChangeCharacterMoralWeaknessUseCase.kt:30)
	at com.soyle.stories.characterarc.changeSectionValue.ChangeSectionValueControllerImpl$setMoralWeakness$1.invokeSuspend(ChangeSectionValueControllerImpl.kt:46)
	at com.soyle.stories.characterarc.changeSectionValue.ChangeSectionValueControllerImpl$setMoralWeakness$1.invoke(ChangeSectionValueControllerImpl.kt)
	at com.soyle.stories.characterarc.changeSectionValue.ChangeSectionValueControllerImpl$setMoralWeakness$1.invoke(ChangeSectionValueControllerImpl.kt)
	at com.soyle.stories.common.AsyncThreadTransformer$async$1$1.invokeSuspend(ThreadTransformerImpl.kt:12)
	at com.soyle.stories.common.AsyncThreadTransformer$async$1$1.invoke(ThreadTransformerImpl.kt)
	at com.soyle.stories.common.AsyncThreadTransformer$async$1$1.invoke(ThreadTransformerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
	at com.soyle.stories.common.AsyncThreadTransformer$async$1.invokeSuspend(ThreadTransformerImpl.kt:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by b-camphart** [comment]
@ryanreso1993 please verify with new release

**Comment by ryanreso1993** [comment]
> @ryanreso1993 please verify with new release

I was unable to reproduce #88 as I can't find the Character Conflict tool where it lists the Central Conflict, Desire, Psychological Weakness, etc.

**Comment by b-camphart** [comment]
You can find it in the theme list now

**Comment by b-camphart** [comment]
@ryanreso1993 giving this one a bump.  Can't finalize v0.13.0 until these are all confirmed fixed.

**Comment by ryanreso1993** [comment]
Confirmed half fixed. Repeat these steps to reproduce a similar error:
1. Create Project
2. Create Character
3. Create Character arc for said cahracter
4. Open the Themes tab
5. Open Examine Character Conflict for the arc
6.  Set perspective character as created character
7. Write in Moral Weakness
8. Write in Desire
9. Click in Psychological Weakness

What I expect: The text in Moral Weakness stays.

What actually happens: The text in Moral Weakness disappears.

**Comment by b-camphart** [comment]
@ryanreso1993 try now

**Comment by ryanreso1993** [comment]
Confirmed fixed v0.13.0 Pre-Release 3! 🥳
